name: Build

on:
  workflow_call:
  workflow_run:
    workflows: ["CI"]  # Trigger build after CI Workflow completes successfully
    types:
      - completed
  workflow_dispatch:  # Manual trigger

env:
    PYTHON_VERSION: 3.9
    POETRY_VERSION: 1.8.4

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v9
      with:
        poetry-version: ${{ env.POETRY_VERSION }}

    - name: Check Poetry version
      run: poetry --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install --all-extras

    - name: Build Python package
      run: poetry build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist
          !dist/**/*.md
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: output/test/code-coverage.html